version: "3"
services:
  app_frontend:
    build: ./front-end
    container_name: app_frontend
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_backend

  banco:
    image: postgres
    container_name: banco
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env
    volumes:
      - volume_banco:/var/lib/postgresql/data

  app_backend:
    build: ./back-end
    container_name: app_backend
    ports:
      - 5000:5000
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run start"
    depends_on:
      - banco

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_frontend

volumes:
  build_react:
  volume_banco:
